### ISSUE TITLE
Unable to use own types 

### ISSUE THREAD

**Issue by kruczekrobert** [meteran/gnext#13]
```go
type MyType string

type Response struct {
 Type MyType json:"type"
}
```

It falls into an endless loop when trying to create a schema for documentation

**Comment by meteran** [comment]
I found the problem. It affects part of primitives with the custom types. I've already fixed it. Will be part of a next release.

**Comment by meteran** [comment]
New release is available: https://github.com/meteran/gnext/releases/tag/v0.7.0
It fixes the discussed issue.
