### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by akhilgupta1093** [meteran/gnext#17]
How can we resolve a CORS issue?

**Comment by kruczekrobert** [comment]
What exactly do you mean?

**Comment by meteran** [comment]
Hi @akhilgupta1093, for now we don't have a dedicated middleware for this purpose yet. But the framework is compatible with native gin middlewares, so you can use e.g. github.com/gin-contrib/cors library:

```go
router := gnext.Router()

corsConfig := cors.DefaultConfig()
corsConfig.AllowCredentials = true
corsConfig.AllowAllOrigins = true
corsConfig.AddAllowHeaders("Authorization")

router.Engine().Use(cors.New(corsConfig))
```

**Comment by kruczekrobert** [comment]
@akhilgupta1093 Does the problem still exist?

**Comment by akhilgupta1093** [comment]
Hi, not for this reason, but I decided not to use this library. Seems like the standard gin middleware should fix the issue, thanks.
