### ISSUE TITLE
openapi3.ExtentionProps is unavailable in latest versions of kin-openapi

### ISSUE THREAD

**Issue by snimshchikov** [meteran/gnext#24]
```
...\mod\github.com\meteran\gnext@v0.8.0\docs\structures.go:30:26: undefined: openapi3.ExtensionProps
...\mod\github.com\meteran\gnext@v0.8.0\docs\docs.go:46:5: unknown field ExtensionProps in struct literal of type openapi3.Info
```
`openapi3.ExtensionProps` should be replaced with `map[string]interface{}`
`ExtensionProps: options.ExtensionProps` should be replaced with `Extensions: options.ExtensionProps`
https://github.com/getkin/kin-openapi/blob/994d4f01c1e8dd613805668a7c10b568547f7789/README.md?plain=1#L279

**Comment by snimshchikov** [comment]
temporary solution is to downgrade to kin-openapi v0.112.0

**Comment by kruczekrobert** [comment]
Hi, we're happy to see your interest in gnext 👋

Upgrading the kin-openapi library and fixing this issue has been submitted for review.

**Comment by meteran** [comment]
New release v0.9.0 has covered new version of `kin-openapi`.
